### ISSUE TITLE
modal-quickview (Product Loop widget) loads full product pages in the background

### ISSUE THREAD

**Issue by JurekSIN** [athemes/Leto#36]
Hello,

It came to our attention that the Product Loop widget loads all images, not just the thumbail that is displayed.

After the thumbail, price and link is displayed, the full product page is loading in the background with this code and following after it:

```
<div id="modal-quickview" class="mfp-hide product-modal"> 
<div class="mosal-quickview_content single-product woocommerce">
```

Is there a reason for this and a way to fix it? Obviously loading all product images on homepage widget is terrible for SEO and Google indexing.

Looking forward to hearing from the team,

Jurek
![capturfiles_3536](https://user-images.githubusercontent.com/24252068/45205093-7350ca80-b281-11e8-8931-38dac0219d6e.png)

**Comment by vlad706** [comment]
Hey,

Sorry about the late reply here.
You are indeed correct and there is now an option to display only the featured image rather than the whole gallery.
Also, you can disable the modal completely which will remove from the source all things loaded by the modal.

Vlad
